// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Awsvpc
{
    [AwsvpcResourceType("awsvpc:index:Vpc")]
    public partial class Vpc : Pulumi.ComponentResource
    {
        /// <summary>
        /// The IDs of the created private subnets
        /// </summary>
        [Output("privateSubnetIds")]
        public Output<ImmutableArray<string>> PrivateSubnetIds { get; private set; } = null!;

        /// <summary>
        /// The IDs of the created public subnets
        /// </summary>
        [Output("publicSubnetIds")]
        public Output<ImmutableArray<string>> PublicSubnetIds { get; private set; } = null!;

        /// <summary>
        /// The AWS-assigned ID of the VPC
        /// </summary>
        [Output("vpcId")]
        public Output<string> VpcId { get; private set; } = null!;


        /// <summary>
        /// Create a Vpc resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Vpc(string name, VpcArgs args, ComponentResourceOptions? options = null)
            : base("awsvpc:index:Vpc", name, args ?? new VpcArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class VpcArgs : Pulumi.ResourceArgs
    {
        [Input("availabilityZoneNames", required: true)]
        private List<Input<string>>? _availabilityZoneNames;

        /// <summary>
        /// List of availability zones to use for your VPC.
        /// </summary>
        public List<Input<string>> AvailabilityZoneNames
        {
            get => _availabilityZoneNames ?? (_availabilityZoneNames = new List<Input<string>>());
            set => _availabilityZoneNames = value;
        }

        /// <summary>
        /// The primary CIDRv4 block to be associated with the VPC.
        /// </summary>
        [Input("baseCidr", required: true)]
        public string BaseCidr { get; set; } = null!;

        /// <summary>
        /// Whether to create a private hosted zone attached to the VPC.
        /// </summary>
        [Input("createPrivateZone")]
        public bool? CreatePrivateZone { get; set; }

        /// <summary>
        /// Whether to add the DynamoDB endpoint to the VPC.
        /// </summary>
        [Input("enableDynamoDBEndpoint")]
        public Input<bool>? EnableDynamoDBEndpoint { get; set; }

        /// <summary>
        /// Whether to add the S3 endpoint to the VPC.
        /// </summary>
        [Input("enableS3Endpoint")]
        public Input<bool>? EnableS3Endpoint { get; set; }

        [Input("tags")]
        private InputMap<string>? _tags;

        /// <summary>
        /// Tags to be applied to each created resource.
        /// </summary>
        public InputMap<string> Tags
        {
            get => _tags ?? (_tags = new InputMap<string>());
            set => _tags = value;
        }

        /// <summary>
        /// The name of the private zone to create if createPrivateZone is set to true.
        /// </summary>
        [Input("zoneName")]
        public Input<string>? ZoneName { get; set; }

        public VpcArgs()
        {
        }
    }
}
